# import python libraries

In [48]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# loading data as csv file

In [112]:
data = pd.read_csv("nba_draft_combine_all_years.csv")

In [114]:
data.head()

,Unnamed: 0,Player,Year,Draft pick,Height (No Shoes),Height (With Shoes),Wingspan,Standing reach,Vertical (Max),Vertical (Max Reach),Vertical (No Step),Vertical (No Step Reach),Weight,Body Fat,Hand (Length),Hand (Width),Bench,Agility,Sprint
0,0,Blake Griffin,2009,1.0,80.50,82.00,83.25,105.0,35.5,140.5,32.0,137.0,248.0,8.2,NaN,NaN,22.0,10.95,3.28
1,1,Terrence Williams,2009,11.0,77.00,78.25,81.00,103.5,37.0,140.5,30.5,134.0,213.0,5.1,NaN,NaN,9.0,11.15,3.18
2,2,Gerald Henderson,2009,12.0,76.00,77.00,82.25,102.5,35.0,137.5,31.5,134.0,215.0,4.4,NaN,NaN,8.0,11.17,3.14
3,3,Tyler Hansbrough,2009,13.0,80.25,81.50,83.50,106.0,34.0,140.0,27.5,133.5,234.0,8.5,NaN,NaN,18.0,11.12,3.27
4,4,Earl Clark,2009,14.0,80.50,82.25,86.50,109.5,33.0,142.5,28.5,138.0,228.0,5.2,NaN,NaN,5.0,11.17,3.35

# information related to dataset

In [116]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                517 non-null    int64
 1   Player                    517 non-null    object
 2   Year                      517 non-null    int64
 3   Draft pick                384 non-null    float64
 4   Height (No Shoes)         517 non-null    float64
 5   Height (With Shoes)       516 non-null    float64
 6   Wingspan                  517 non-null    float64
 7   Standing reach            517 non-null    float64
 8   Vertical (Max)            450 non-null    float64
 9   Vertical (Max Reach)      450 non-null    float64
 10  Vertical (No Step)        450 non-null    float64
 11  Vertical (No Step Reach)  450 non-null    float64
 12  Weight                    516 non-null    float64
 13  Body Fat                  514 non-null    float64
 14  Hand (Length)             470 non-null    float64
 15  Hand (Width)              468 non-null    float64
 16  Bench                     284 non-null    float64
 17  Agility                   444 non-null    float64
 18  Sprint                    446 non-null    float64
dtypes: float64(16), int64(2), object(1)
memory usage: 76.9+ KB

# finding the missing value with the help of isnull function

In [83]:
data.isnull()

,Unnamed: 0,Player,Year,Draft pick,Height (No Shoes),Height (With Shoes),Wingspan,Standing reach,Vertical (Max),Vertical (Max Reach),Vertical (No Step),Vertical (No Step Reach),Weight,Body Fat,Hand (Length),Hand (Width),Bench,Agility,Sprint
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
513,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
514,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
515,False,False,False,True,False,False,False,False,True,True,True,True,False,False,False,False,True,True,True
516,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False

# number of missing column

In [118]:
data.isnull().sum()

Unnamed: 0                    0
Player                        0
Year                          0
Draft pick                  133
Height (No Shoes)             0
Height (With Shoes)           1
Wingspan                      0
Standing reach                0
Vertical (Max)               67
Vertical (Max Reach)         67
Vertical (No Step)           67
Vertical (No Step Reach)     67
Weight                        1
Body Fat                      3
Hand (Length)                47
Hand (Width)                 49
Bench                       233
Agility                      73
Sprint                       71
dtype: int64

# finding sum of total null values

In [120]:
data.isnull().sum().sum()

879

# shape of data

In [94]:
data.shape

(517, 19)

# removing null values

In [126]:
data.dropna(inplace=True)

# again checking null values

In [129]:
data.isnull().sum()

Unnamed: 0                  0
Player                      0
Year                        0
Draft pick                  0
Height (No Shoes)           0
Height (With Shoes)         0
Wingspan                    0
Standing reach              0
Vertical (Max)              0
Vertical (Max Reach)        0
Vertical (No Step)          0
Vertical (No Step Reach)    0
Weight                      0
Body Fat                    0
Hand (Length)               0
Hand (Width)                0
Bench                       0
Agility                     0
Sprint                      0
dtype: int64

In [131]:
data.isnull().sum().sum()

0

# exporting csv file to excel

In [131]:
data.to_csv("nba_draft_combine_all_years.csv",index=False)